# The storage system used for storing training artifacts
# This is optional if modelbox is started as a metadata service
# Possible values - filesystem, s3
artifact_storage: "filesystem"

# Storage system used for storing metadata related to training artifacts
# such as models and checkpoints, and lineage of artifacts
# Possible values - ephemeral, mysql, postgres
metadata_storage: "postgres"

# Storage system to use for storing metrics.
# Possible values - inmemory, timescaledb
metrics_storage: "timescaledb"

# Interface on which the metadata service is listening for network connections
grpc_listen_addr: ":8085"
http_listen_addr: ":8081"

# Interface on which the admin/scheduler server is listening
admin_listen_addr: ":8085"

# Tick duration of the scheduler
scheduler_tick_duration: 5s

cluster_membership: "mysql"

# Additional configuration for filesystem based blob_storage
artifact_storage_filesystem:
  base_dir: "/tmp/modelboxblobs"

artifact_storage_s3:
  region: "us-east-1"
  bucket: "modelbox-artifacts"

# Additional configuration for integrated metadata storage
metadata_storage_sqlite3:
  path: "/tmp/modelbox.dat"


# Additional configuration for metadata storage in PostgreSQL
metadata_storage_postgres:
  host: "172.20.0.5"
  port: 5432
  username: "postgres"
  password: "foo"
  dbname: "modelbox"

# Additional configuration for metadata storage in MySQL
metadata_storage_mysql:
  host:      "172.20.0.6"
  port:      3306
  username:  "root"
  password:  "foo"
  dbname:    "modelbox"

# Configuration optin for timescaledb
metrics_storage_timescaledb:
  host: "172.20.0.7"
  port: 5432
  username: "postgres"
  password: "foo"
  dbname:   "modelbox_metrics"

sql_cluster_membership:
  lease_interval: 5s
  stale_heartbeat_duration: 30s