# The storage system used for storing training artifacts
# This is optional if modelbox is started as a metadata service
# Possible values - filesystem, s3
blob_storage = "filesystem"

# Storage system used for storing metadata related to training artifacts
# such as models and checkpoints, and lineage of artifacts
# Possible values - integrated, mysql, postgres
metadata_storage = "integrated"

# Storage system to use for storing metrics.
# Possible values - inmem, timescaledb
metrics_storage = "inmem"

# Interface on which the metadata service is listening for network connections
listen_addr = ":8085"

# Additional configuration for filesystem based blob_storage
[blob_storage_filesystem]
base_dir = "/tmp/modelboxblobs"

# Additional configuration for integrated metadata storage
[metadata_storage_integrated]
path = "/tmp/modelbox.dat"

# Additional configuration for metadata storage in PostgreSQL
[metadata_storage_postgres]
host = "172.17.0.3"
port = 5432
username = "postgres"
password = "foo"
dbname   = "modelbox"

# Additional configuration for metadata storage in MySQL 
[metadata_storage_mysql]
host     = "172.17.0.2"
port     = 3306
username = "root"
password = "foo"
dbname   = "modelbox"

# Configuration optin for timescaledb
[metrics_storage_timescaledb]
host = "172.17.0.4"
port = 5432
username = "postgres"
password = "foo"
dbname   = "modelbox_metrics" 